### ISSUE TITLE
Gedit 3.12

### ISSUE THREAD

**Issue by arigit** [jefferyto/gedit-toggle-text-wrapping#1]
Not working with gedit 3.12. 
The menu option for wrapping does not add itself to the "tools" menu, no new icon show up in the bar, and the shortcut "ctrl shift B" does not work either.

**Comment by jefferyto** [comment]
Thanks for submitting this - unfortunately I'm not sure when I'll have time to get it working in 3.12 :frowning:

**Comment by twsquad** [comment]
Same with gedit 3.18.3
No menu options, no new icon, and the shortcut "Ctrl Shift B" does not work.

Traceback (most recent call last):
  File "/.../gedit/plugins/toggletextwrapping/__init__.py", line 71, in do_activate
    manager = window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
  File "/.../gedit/plugins/toggletextwrapping/__init__.py", line 124, in do_update_state
    action = self._action
AttributeError: 'ToggleTextWrappingPlugin' object has no attribute '_action'
  File "/.../gedit/plugins/toggletextwrapping/__init__.py", line 106, in do_deactivate
    disconnect_handlers(self, self._settings)
AttributeError: 'ToggleTextWrappingPlugin' object has no attribute '_settings'

**Comment by jefferyto** [comment]
This plugin hasn't been updated to work with the gedit 3.12 redesign. Also, in gedit 3.14 and newer, clicking the line/column number in the status bar opens a menu where you can toggle line wrapping for the current tab, so this plugin isn't strictly necessary anymore.
